"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    "iconfile": "icon.ico",
    "packages": ["pynput"]
}

setup(
    app=APP,
    name="Superfarm 4.0 Hypixel Farming Helper",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
