"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    "packages": ["pynput"],
    "iconfile": "icon.icns",
    "optimize": 2,
}

setup(
    app=APP,
    name="Hypixel Farming Helper",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
